version: '3.8'
services:
  pki:
    image: ghcr.io/wirepact/k8s-pki:1.1.0
    command:
      - '-local'
    ports:
      - 9090:8080

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/translator-realm.json
    command:
      - '-Dkeycloak.profile=preview'
      - '-Dkeycloak.profile.feature.token_exchange=enabled'
      - '-b 0.0.0.0'
    networks:
      - app-net
    ports:
      - 8080:8080
    volumes:
      - ./hack/translator-realm.json:/tmp/translator-realm.json:ro

  app:
    build:
      context: example/app
      dockerfile: Dockerfile
    networks:
      - app-net
    command:
      - '-api=http://envoy-api:9000/albums'
    depends_on:
      - envoy-app
    environment:
      ISSUER: http://host.docker.internal:8080/auth/realms/translator
      CLIENT_ID: testoidcapp
      HTTP_PROXY: http://envoy-app:8100

  envoy-app:
    image: envoyproxy/envoy-alpine:v1.20-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.app.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - app-net
    ports:
      - 8000:8000
      - 8100:8100

  api:
    build:
      context: example/api
      dockerfile: Dockerfile
    networks:
      - app-net
    environment:
      ISSUER: http://host.docker.internal:8080/auth/realms/translator
      CLIENT_ID: testoidcapi
      CLIENT_SECRET: 816095db-2190-4d77-80e4-a096c6c7a889

  envoy-api:
    image: envoyproxy/envoy-alpine:v1.20-latest
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level ext_authz:trace
    volumes:
      - ./hack/envoy-config.api.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - app-net
    ports:
      - 9000:9000

networks:
  app-net:
    driver: bridge
